apiVersion: v1
kind: Service
metadata:
  name: {{ include "getclientele.fullname" . }}-vector
spec:
  selector:
    app: vector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: {{ .Values.service.type | default "ClusterIP" }}
