# Generated by Django 6.0 on 2025-12-22 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('is_mobile', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=512, blank=True)),
                ('categories', models.JSONField(default=list, blank=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('stock', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='products', to='vendors.Vendor')),
            ],
        ),
    ]
